### ISSUE TITLE
Running control-service for the first time without any modifications is broken

### ISSUE THREAD

**Issue by YanaZhivkova** [vmware/versatile-data-kit#447]
**Describe the bug**
When you check out control-service for the first time and try to run it, it does not work unless you have a local k8s running.

**Steps To Reproduce**
1. Open versatile-data-kit/projects/control-service in IntelliJ
2. Remove all currently running k8s clusters from your system
3. Make sure you have no changes in control-service/projects/pipelines_control_service/src/main/resources/application.properties
3. Try to run control-service/projects/pipelines_control_service/src/main/java/com/vmware/taurus/ServiceApp.java
4. See error:
Caused by: java.lang.NullPointerException: null
	at io.kubernetes.client.util.ClientBuilder.kubeconfig(ClientBuilder.java:225)
	at com.vmware.taurus.service.KubernetesService.afterPropertiesSet(KubernetesService.java:231)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 71 common frames omitted

**Expected behavior**
The service should run without the need to set up a k8s cluster. If this is not possible, setting up the local k8s should be mentioned in the documentation as a prerequisite.

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
