### ISSUE TITLE
[vdk-control-cli] Misconfigured config file breaks vdk deploy on windows

### ISSUE THREAD

**Issue by doks5** [vmware/versatile-data-kit#621]
**Describe the bug**
Tried to edit the config.ini of a data job in notepad on windows. After copying a cron schedule and an email address from a web page and pasting it in the config file, `vdk deploy -n <job-name> -t <team-name> -p <job-directory>` caused an exception (logs added below). From the stacktrace, it is hard to tell what exactly went wrong.

**Steps To Reproduce**
1. Create a data job 
2. Edit the config.ini in notepad by copy-pasting cron schedule or email address from another location, where the formatting of the text is different, or add a special symbol on one of the lines of the file.
3. Try deploying the job with `vdk deploy -n <job-name> -t <team-name> -p <job-directory>`

**Expected behavior**
The job is deployed, or at least a meaningful error message is returned.

**Logs**
```bash
Exiting with exception. 
Traceback (most recent call last):
  File "c:\some\directory\venv\taurus\lib\site-packages\vdk\internal\cli_entry.py", line 132, in vdk_main
    exit_code = cast(InternalHookSpecs, plugin_registry.hook()).vdk_cli_execute(
  File "c:\some\directory\venv\taurus\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\some\directory\venv\taurus\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\some\directory\venv\taurus\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "c:\some\directory\venv\taurus\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\some\directory\venv\taurus\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\some\directory\venv\taurus\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\some\directory\venv\taurus\lib\site-packages\vdk\internal\cli_entry.py", line 95, in vdk_cli_execute
    exit_code = root_command(
  File "c:\some\directory\venv\taurus\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\some\directory\venv\taurus\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\some\directory\venv\taurus\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\some\directory\venv\taurus\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\some\directory\venv\taurus\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\some\directory\venv\taurus\lib\site-packages\vdk\internal\control\utils\cli_utils.py", line 94, in check
    return f(*args, **kwargs)
  File "c:\some\directory\venv\taurus\lib\site-packages\vdk\internal\control\command_groups\job\deploy_cli.py", line 171, in deploy
    return cmd.create(name, team, job_path, reason, output)
  File "c:\some\directory\venv\taurus\lib\site-packages\vdk\internal\control\rest_lib\rest_client_errors.py", line 55, in decorated
    result = fn(*args, **kwargs)
  File "c:\some\directory\venv\taurus\lib\site-packages\vdk\internal\control\command_groups\job\deploy_cli_impl.py", line 255, in create
    job_config = JobConfig(job_path)
  File "c:\some\directory\venv\taurus\lib\site-packages\vdk\internal\control\job\job_config.py", line 30, in __init__
    self._config_ini.read(self._config_file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\some\\user\\directory\\calculate-cust-tred\\config.ini', line: 1
'ï»¿; Supported format: https://docs.python.org/3/library/configparser.html#supported-ini-file-structure\n'

```

**Version  (please complete the following information):**
 - OS: Windows
 - Version: VDK Version: 0.0.395832173
 
**Additional context**
Logs added above.

**Comment by doks5** [comment]
The issue seems to be caused by notepad adding BOM at the beginning of the file: https://stackoverflow.com/a/18846911
