### ISSUE TITLE
"vdk server --install"  command fails

### ISSUE THREAD

**Issue by vecorro** [vmware/versatile-data-kit#891]
**Describe the bug**
The `vdk server --install` command fails with the following error message:

>Traceback (most recent call last):
  File "/Users/kike/opt/miniconda3/envs/vmw_vdk/bin/vdk", line 5, in <module>
    from vdk.internal.cli_entry import main
  File "/Users/kike/opt/miniconda3/envs/vmw_vdk/lib/python3.9/site-packages/vdk/internal/cli_entry.py", line 13, in <module>
    from vdk.api.plugin.core_hook_spec import CoreHookSpecs
  File "/Users/kike/opt/miniconda3/envs/vmw_vdk/lib/python3.9/site-packages/vdk/api/plugin/core_hook_spec.py", line 8, in <module>
    from vdk.api.plugin.plugin_registry import IPluginRegistry
  File "/Users/kike/opt/miniconda3/envs/vmw_vdk/lib/python3.9/site-packages/vdk/api/plugin/plugin_registry.py", line 46, in <module>
    HookCallResult = pluggy.callers._Result
AttributeError: module 'pluggy' has no attribute 'callers'

**Steps To Reproduce**
>- Created a clean Python 3.9.12 virtual env using conda
-Then ran `pip install quickstart-vdk`
-Then ran `pip install airflow-provider-vdk` and got the following warnings:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
vdk-core 0.3.572339461 requires click==8.*, but you have click 7.1.2 which is incompatible.
vdk-core 0.3.572339461 requires pluggy==0.*, but you have pluggy 1.0.0 which is incompatible.
vdk-control-cli 1.3.577021265 requires click==8.*, but you have click 7.1.2 which is incompatible.
vdk-control-cli 1.3.577021265 requires pluggy==0.*, but you have pluggy 1.0.0 which is incompatible.`
-Then ran ` vdk server --install` and got the following error:
`Traceback (most recent call last):
  File "/Users/kike/opt/miniconda3/envs/vmw_vdk/bin/vdk", line 5, in <module>
    from vdk.internal.cli_entry import main
  File "/Users/kike/opt/miniconda3/envs/vmw_vdk/lib/python3.9/site-packages/vdk/internal/cli_entry.py", line 13, in <module>
    from vdk.api.plugin.core_hook_spec import CoreHookSpecs
  File "/Users/kike/opt/miniconda3/envs/vmw_vdk/lib/python3.9/site-packages/vdk/api/plugin/core_hook_spec.py", line 8, in <module>
    from vdk.api.plugin.plugin_registry import IPluginRegistry
  File "/Users/kike/opt/miniconda3/envs/vmw_vdk/lib/python3.9/site-packages/vdk/api/plugin/plugin_registry.py", line 46, in <module>
    HookCallResult = pluggy.callers._Result
AttributeError: module 'pluggy' has no attribute 'callers'`

**Version  (please complete the following information):**
 - OS: macOS 12.4 (21F79)
 -  Python 3.9.12 
 - Versatile Data Kit (VDK) Version: 0.3.572339461

**Additional context**
After the installation of airflow-provider-vdk vdk got totally unusable as with any command it throws the `AttributeError: module 'pluggy' has no attribute 'callers'` error.

**Comment by gageorgiev** [comment]
This issue was caused by pluggy 1.0 renaming its callers module to _callers. As pluggy 1.0 is supported by VDK now, this issue has been resolved.
